"""
session_reader.py

Reads and filters Claude session-meta JSON files from
~/.codex/usage-data/session-meta/*.json
"""

import json
from datetime import date, datetime
from pathlib import Path
from typing import Any


# ── Constants ────────────────────────────────────────────────────────────────

SESSION_META_DIR = Path.home() / ".claude" / "usage-data" / "session-meta"

AUTOMATED_MARKERS: tuple[str, ...] = (
    "return only a json",
    "eng-buddy",
    "engineering buddy",
)


# ── Helpers ──────────────────────────────────────────────────────────────────

def _parse_first_json(content: str) -> dict[str, Any]:
    """
    Return the first JSON object found in *content*.

    Handles files that accidentally contain multiple concatenated JSON objects
    by walking the brace depth and stopping at the first balanced closing brace.
    """
    content = content.strip()
    if not content.startswith("{"):
        raise ValueError("Content does not start with '{'")

    # Fast path: the whole file is a single valid JSON object.
    try:
        return json.loads(content)
    except json.JSONDecodeError:
        pass

    # Slow path: extract the first balanced object manually.
    brace_depth = 0
    in_string = False
    escape_next = False

    for idx, ch in enumerate(content):
        if escape_next:
            escape_next = False
            continue
        if ch == "\\" and in_string:
            escape_next = True
            continue
        if ch == '"':
            in_string = not in_string
            continue
        if in_string:
            continue
        if ch == "{":
            brace_depth += 1
        elif ch == "}":
            brace_depth -= 1
            if brace_depth == 0:
                return json.loads(content[: idx + 1])

    raise ValueError("Could not find a complete JSON object in content")


def _parse_start_time(raw: str) -> date:
    """Parse an ISO-8601 timestamp (with optional trailing 'Z') to a ``date``."""
    normalized = raw.replace("Z", "+00:00")
    return datetime.fromisoformat(normalized).date()


def _is_automated(session: dict[str, Any]) -> bool:
    """Return True if the session was generated by an automated tool."""
    first_prompt: str = session.get("first_prompt") or ""
    lowered = first_prompt.lower()
    return any(marker in lowered for marker in AUTOMATED_MARKERS)


def _is_ultra_short(session: dict[str, Any]) -> bool:
    """Return True when a session is too brief to be meaningful."""
    return (
        session.get("user_message_count", 0) <= 2
        and session.get("duration_minutes", 0) <= 1
    )


# ── Public API ───────────────────────────────────────────────────────────────

def read_sessions(start_date: str, end_date: str) -> dict[str, Any]:
    """
    Read and filter session-meta files within a date range.

    Args:
        start_date: ISO date string (YYYY-MM-DD) — inclusive lower bound.
        end_date:   ISO date string (YYYY-MM-DD) — inclusive upper bound.

    Returns:
        {
            "sessions": list[dict],  # filtered session-meta dicts, sorted
                                     # ascending by start_time
            "stats": {
                "total_found":          int,  # files successfully parsed
                "filtered_interactive": int,  # sessions kept
                "excluded_automated":   int,
                "excluded_short":       int,
                "errors":               int,  # files that could not be parsed
            }
        }
    """
    start = date.fromisoformat(start_date)
    end = date.fromisoformat(end_date)

    stats: dict[str, int] = {
        "total_found": 0,
        "filtered_interactive": 0,
        "excluded_automated": 0,
        "excluded_short": 0,
        "errors": 0,
    }

    kept: list[dict[str, Any]] = []

    for filepath in SESSION_META_DIR.glob("*.json"):
        # ── Parse ────────────────────────────────────────────────────────────
        try:
            content = filepath.read_text(errors="replace")
            session = _parse_first_json(content)
        except Exception:
            stats["errors"] += 1
            continue

        # ── Date range filter ────────────────────────────────────────────────
        try:
            session_date = _parse_start_time(session["start_time"])
        except (KeyError, ValueError, TypeError):
            stats["errors"] += 1
            continue

        if not (start <= session_date <= end):
            continue

        stats["total_found"] += 1

        # ── Exclusion: automated ─────────────────────────────────────────────
        if _is_automated(session):
            stats["excluded_automated"] += 1
            continue

        # ── Exclusion: ultra-short ───────────────────────────────────────────
        if _is_ultra_short(session):
            stats["excluded_short"] += 1
            continue

        kept.append(session)
        stats["filtered_interactive"] += 1

    # ── Sort by start_time ascending ─────────────────────────────────────────
    kept.sort(key=lambda s: s.get("start_time", ""))

    return {"sessions": kept, "stats": stats}
